all:
  children:
    proxmox:
      hosts:
        pve1:
          ansible_host: 192.168.5.11
        pve2:
          ansible_host: 192.168.5.12
        pve3:
          ansible_host: 192.168.5.13
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
