old_dc_ctids: [100, 101]

# Basis-Parameter für die Zamba-Container
zmb_domain_lower: amazonistan.intranet
zmb_domain_upper: AMAZONISTAN.INTRANET
zmb_net_bridge: vmbr3
zmb_net_vlan: "100"
zmb_gw: 192.168.100.1
zmb_dns_primary: 192.168.100.241
zmb_dns_secondary: 1.1.1.1

# Speicher
zmb_template_storage: cephfs
zmb_rootfs_storage: raidpool
zmb_sharefs_storage: raidpool

# Größen
zmb_rootfs_size_gb: "32"
zmb_sharefs_size_gb: "256"

# Ressourcen
zmb_mem_mb: "4096"
zmb_swap_mb: "1024"
zmb_threads: "0"

# Admin
zmb_admin_user: administrator
zmb_admin_pass: "dArkn3$s"

# feste IPs
zmb_ad_ip: 192.168.100.241
zmb_ad_join_ip: 192.168.100.242
